alter table CUBAREST_UPDATE_UNIT add constraint FK_CUBAREST_UPDATE_UNIT_ON_DATA_THEME foreign key (DATA_THEME_ID) references CUBAREST_DATA_THEME(ID);
create index IDX_CUBAREST_UPDATE_UNIT_ON_DATA_THEME on CUBAREST_UPDATE_UNIT (DATA_THEME_ID);
